// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type CategoryLarge struct {
	CategoryLargeID string `json:"categoryLargeId"`
	CategoryName    string `json:"categoryName"`
}

type NewCategoryLarge struct {
	CategoryName string `json:"categoryName"`
}
