// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

import (
	"github.com/so-heee/graphql-example/plan2/graph/pagination"
	"strings"
)

func TodoOrderToPaginationOrders(orders []*TodoOrder) []*pagination.Order {
	paginationOrders := make([]*pagination.Order, len(orders))

	for i, o := range orders {
		paginationOrders[i] = &pagination.Order{Field: strings.ToLower(string(*o.Field)), Direction: pagination.Direction(*o.Direction)}
	}

	return paginationOrders
}

func UserOrderToPaginationOrders(orders []*UserOrder) []*pagination.Order {
	paginationOrders := make([]*pagination.Order, len(orders))

	for i, o := range orders {
		paginationOrders[i] = &pagination.Order{Field: strings.ToLower(string(*o.Field)), Direction: pagination.Direction(*o.Direction)}
	}

	return paginationOrders
}
